export const dashboardProjectPreviewDemo = [
  {
    id: 23942934892,
    title:
      'Background research (Context study, Market study, technology trend, future projections)',
    created: 'April 01, 2022',
    proposalsRecived: 32,
    category: 'Web & App Design',
    expires: 'Nov 11, 2023',
    cost: 2884000,
    pricingtype: 'fixed',
    status: 'published',
  },
  {
    id: 23942934892,
    title: 'Social media marketing campaign',
    created: 'May 15, 2022',
    proposalsRecived: 12,
    category: 'Marketing & Advertising',
    expires: 'Dec 31, 2022',
    cost: 850000,
    pricingtype: 'fixed',
    status: 'published',
  },
  {
    id: 23942934892,
    title: 'Cloud migration and optimization',
    created: 'June 30, 2022',
    proposalsRecived: 6,
    category: 'Cloud Computing',
    expires: 'Jan 31, 2023',
    cost: 1500000,
    pricingtype: 'hourly',
    status: 'published',
  },
  {
    id: 23942934892,
    title: 'Interactive e-learning platform',
    created: 'July 25, 2022',
    proposalsRecived: 18,
    category: 'Education Technology',
    expires: 'Feb 28, 2023',
    cost: 5400000,
    pricingtype: 'fixed',
    status: 'published',
  },
  {
    id: 23942934892,
    title:
      'Development of an AI-powered personal shopping assistant application for mobile devices',
    created: 'July 14, 2022',
    proposalsRecived: 12,
    category: 'Mobile App Development',
    expires: 'Dec 31, 2023',
    cost: 5000000,
    pricingtype: 'hourly',
    status: 'active',
  },
  {
    id: 23942934892,
    title:
      'Design and implementation of a cloud-based supply chain management system for a large e-commerce platform',
    created: 'January 06, 2022',
    proposalsRecived: 22,
    category: 'Web Development',
    expires: 'June 30, 2023',
    cost: 7500000,
    pricingtype: 'fixed',
    status: 'published',
  },
];
